Repository grpc/grpc-java, pull requests merged in 2018-03, with the labels that each got.

#4222 core,netty: client sends rst stream when server half-closes
  core/src/main/java/io/grpc/internal/AbstractClientStream.java
  netty/src/main/java/io/grpc/netty/CancelClientStreamCommand.java
  netty/src/main/java/io/grpc/netty/NettyClientHandler.java
  netty/src/main/java/io/grpc/netty/NettyClientStream.java
  netty/src/test/java/io/grpc/netty/NettyClientStreamTest.java
  okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java
Labels: release blocker

#4265 Bump to Guava 20 (1.11 backport)
  build.gradle
  core/build.gradle
  protobuf/build.gradle
  repositories.bzl
  services/build.gradle
Labels: release blocker

#4275 core,netty: client sends rst stream when server half-closes (1.11 backport)
  core/src/main/java/io/grpc/internal/AbstractClientStream.java
  netty/src/main/java/io/grpc/netty/CancelClientStreamCommand.java
  netty/src/main/java/io/grpc/netty/NettyClientHandler.java
  netty/src/main/java/io/grpc/netty/NettyClientStream.java
  netty/src/test/java/io/grpc/netty/NettyClientStreamTest.java
  okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java
Labels: TODO:release blocker

#4277 okhttp: fix HPACK reader bug (1.11 backport)
  okhttp/third_party/okhttp/java/io/grpc/okhttp/internal/framed/Hpack.java
Labels: TODO:release blocker

#3795 netty,okhttp: handle unresolved proxy addresses (backport to v1.7.x)
  netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
  okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
Labels: Type: Behavior Change, Type: Feature
