Repository grpc/grpc-java, pull requests merged in 2019-11, with the labels that each got.

#6369 interop-testing,benchmarks: publish tar, zip
  benchmarks/build.gradle
  interop-testing/build.gradle
Labels: TODO:backport

#6372 alts: Check Cipher before declaring Conscrypt working
  alts/src/main/java/io/grpc/alts/internal/AesGcmAeadCrypter.java
Labels: TODO:backport, TODO:release blocker

#6389 api: Rename blockingExecutor to offloadExecutor
  api/src/main/java/io/grpc/ForwardingChannelBuilder.java
  api/src/main/java/io/grpc/ManagedChannelBuilder.java
  api/src/main/java/io/grpc/NameResolver.java
  api/src/test/java/io/grpc/NameResolverTest.java
  core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
  core/src/main/java/io/grpc/internal/DnsNameResolver.java
  core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
  core/src/test/java/io/grpc/internal/AbstractManagedChannelImplBuilderTest.java
  core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
  core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
Labels: TODO:backport, TODO:release blocker

#6388 alts: Check Cipher before declaring Conscrypt working (v1.25.x backport)
  alts/src/main/java/io/grpc/alts/internal/AesGcmAeadCrypter.java
Labels: TODO:release blocker

#6380 alts: fix ComputeEngineChannelBuilder class signature (backport v1.25.x)
  alts/src/main/java/io/grpc/alts/ComputeEngineChannelBuilder.java
Labels: TODO:release blocker

#6391 api: Rename blockingExecutor to offloadExecutor (v1.25.x backport)
  api/src/main/java/io/grpc/ForwardingChannelBuilder.java
  api/src/main/java/io/grpc/ManagedChannelBuilder.java
  api/src/main/java/io/grpc/NameResolver.java
  api/src/test/java/io/grpc/NameResolverTest.java
  core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
  core/src/main/java/io/grpc/internal/DnsNameResolver.java
  core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
  core/src/test/java/io/grpc/internal/AbstractManagedChannelImplBuilderTest.java
  core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
  core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
Labels: TODO:release blocker
