Repository grpc/grpc-java, pull requests merged in 2020-05, with the labels that each got.

#6968 5439: InProcessTransport optionally adds causal information to status
  core/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java
  core/src/main/java/io/grpc/inprocess/InProcessTransport.java
  core/src/main/java/io/grpc/internal/ServerImpl.java
  core/src/test/java/io/grpc/inprocess/InProcessTransportTest.java
  core/src/test/java/io/grpc/internal/AbstractTransportTest.java
  core/src/test/java/io/grpc/internal/ServerImplTest.java
Labels: kokoro:run

#7048 NettyClientTransport: use getOrCreate() for new instances of ChannelLogger AttributeKey.
  netty/src/main/java/io/grpc/netty/NettyClientTransport.java
Labels: TODO:backport, TODO:release blocker

#7054 compiler: support proto3 field presence for codegen
  compiler/src/java_plugin/cpp/java_plugin.cpp
Labels: TODO:backport

#7071 stub: Have disableAutoRequest() on server-side
  examples/src/main/java/io/grpc/examples/manualflowcontrol/ManualFlowControlServer.java
  services/src/main/java/io/grpc/protobuf/services/ProtoReflectionService.java
  stub/src/main/java/io/grpc/stub/CallStreamObserver.java
  stub/src/main/java/io/grpc/stub/ClientCallStreamObserver.java
  stub/src/main/java/io/grpc/stub/ServerCallStreamObserver.java
  stub/src/main/java/io/grpc/stub/ServerCalls.java
  stub/src/test/java/io/grpc/stub/ClientCallsTest.java
  stub/src/test/java/io/grpc/stub/ServerCallsTest.java
Labels: TODO:backport
