Repository grpc/grpc-java, pull requests merged in 2021-06, with the labels that each got.

#8209 binder: Remove InternalMetadataHelper.
  binder/src/main/java/io/grpc/binder/ParcelableUtils.java
  binder/src/main/java/io/grpc/binder/internal/InternalMetadataHelper.java
  binder/src/main/java/io/grpc/binder/internal/MetadataHelper.java
Labels: binder

#8271 netty-shaded: Use compile instead of runtime dep in pom for core
  netty/shaded/build.gradle
Labels: TODO:backport

#8275 Update AndroidComponentAddress to wrap a binding Intent.
  binder/src/androidTest/java/io/grpc/binder/BinderChannelSmokeTest.java
  binder/src/androidTest/java/io/grpc/binder/BinderSecurityTest.java
  binder/src/androidTest/java/io/grpc/binder/internal/BinderClientTransportTest.java
  binder/src/main/java/io/grpc/binder/AndroidComponentAddress.java
  binder/src/main/java/io/grpc/binder/ApiConstants.java
  binder/src/main/java/io/grpc/binder/BinderServerBuilder.java
  binder/src/main/java/io/grpc/binder/internal/BinderTransport.java
  binder/src/main/java/io/grpc/binder/internal/ServiceBinding.java
  binder/src/test/java/io/grpc/binder/AndroidComponentAddressTest.java
  binder/src/test/java/io/grpc/binder/BinderServerBuilderTest.java
  binder/src/test/java/io/grpc/binder/internal/ServiceBindingTest.java
Labels: kokoro:force-run
