Repository grpc/grpc-java, pull requests merged in 2024-06, with the labels that each got.

#11281 opentelemetry: Add explicit histogram buckets for per-call metrics
  opentelemetry/src/main/java/io/grpc/opentelemetry/GrpcOpenTelemetry.java
  opentelemetry/src/main/java/io/grpc/opentelemetry/internal/OpenTelemetryConstants.java
  opentelemetry/src/test/java/io/grpc/opentelemetry/OpenTelemetryMetricsModuleTest.java
Labels: TODO:backport

#11267 examples: Add GCP CSM Observability example
  examples/example-gcp-csm-observability/README.md
  examples/example-gcp-csm-observability/build.gradle
  examples/example-gcp-csm-observability/csm-client.Dockerfile
  examples/example-gcp-csm-observability/csm-server.Dockerfile
  examples/example-gcp-csm-observability/settings.gradle
  examples/example-gcp-csm-observability/src/main/java/io/grpc/examples/csmobservability/CsmObservabilityClient.java
  examples/example-gcp-csm-observability/src/main/java/io/grpc/examples/csmobservability/CsmObservabilityServer.java
  examples/example-gcp-csm-observability/src/main/proto/helloworld/helloworld.proto
Labels: TODO:backport

#11294 netty:Fix Netty composite buffer merging to be compatible with Netty 4.1.111
  netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java
  netty/src/test/java/io/grpc/netty/NettyAdaptiveCumulatorTest.java
Labels: TODO:backport, TODO:release blocker

#11315 security: Add ExperimentalApi annotation to AdvancedTlsX509KeyManager class.
  util/src/main/java/io/grpc/util/AdvancedTlsX509KeyManager.java
Labels: TODO:backport, TODO:release blocker, kokoro:run
